trigger:
- master

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      # Install required packages
      pip install tgcalls==3.0.0.dev6
      pip install emoji
    displayName: 'Install Dependencies'

  - script: |
      # Download Ultroid installer and run it
      wget https://raw.githubusercontent.com/TeamUltroid/Ultroid/dev/installer.sh
      chmod +x installer.sh
      sudo bash installer.sh --dir="/root/TeamUltroid" --branch=dev --env-file="ultroid/.env"
    displayName: 'Install Ultroid'

  - script: |
      # Run Ultroid bot
      sudo bash action.sh
    displayName: 'Run Ultroid'
